//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.InsertDataServiceOne {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InsertDataServiceOne.IInsertDataService1")]
    public interface IInsertDataService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService1/SetData", ReplyAction="http://tempuri.org/IInsertDataService1/SetDataResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void SetData(string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService1/SetData", ReplyAction="http://tempuri.org/IInsertDataService1/SetDataResponse")]
        System.Threading.Tasks.Task SetDataAsync(string connectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsertDataService1Channel : Client.InsertDataServiceOne.IInsertDataService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertDataService1Client : System.ServiceModel.ClientBase<Client.InsertDataServiceOne.IInsertDataService1>, Client.InsertDataServiceOne.IInsertDataService1 {
        
        public InsertDataService1Client() {
        }
        
        public InsertDataService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsertDataService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertDataService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertDataService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetData(string connectionString) {
            base.Channel.SetData(connectionString);
        }
        
        public System.Threading.Tasks.Task SetDataAsync(string connectionString) {
            return base.Channel.SetDataAsync(connectionString);
        }
    }
}
