//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.InsertDataServiceTwo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InsertDataServiceTwo.IInsertDataService2")]
    public interface IInsertDataService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService2/SetData", ReplyAction="http://tempuri.org/IInsertDataService2/SetDataResponse")]
        void SetData(string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService2/SetData", ReplyAction="http://tempuri.org/IInsertDataService2/SetDataResponse")]
        System.Threading.Tasks.Task SetDataAsync(string connectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsertDataService2Channel : Client.InsertDataServiceTwo.IInsertDataService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertDataService2Client : System.ServiceModel.ClientBase<Client.InsertDataServiceTwo.IInsertDataService2>, Client.InsertDataServiceTwo.IInsertDataService2 {
        
        public InsertDataService2Client() {
        }
        
        public InsertDataService2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsertDataService2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertDataService2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertDataService2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetData(string connectionString) {
            base.Channel.SetData(connectionString);
        }
        
        public System.Threading.Tasks.Task SetDataAsync(string connectionString) {
            return base.Channel.SetDataAsync(connectionString);
        }
    }
}
